export enum EventType {
	OPEN_STREAM = 'OPEN_STREAM',
	CLOSE_STREAM = 'CLOSE_STREAM',
	CONNECTION = 'CONNECTION',
	DECONNECTION = 'DECONNECTION',
	MUTE = 'MUTE',
	UNMUTE = 'UNMUTE',
	DEAF = 'DEAF',
	UNDEAF = 'UNDEAF',
}
